name: dart_gbase_client
publish_to: none
description: A starting point for Dart libraries or applications.
version: 1.0.1+2

# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0



dependencies:
  path: ^1.8.0
  web_socket_channel: ^2.2.0
  http_parser: ^4.0.1
  http: ^0.13.4
